### PR TITLE
Master fixes

### PR DESCRIPTION
**Pull request by igr**
Added:

+ withAttachable
+ withDriver

### CODE REVIEW

**Comment by cirocosta** [comment]
it also includes all the new commits after our current master, maybe we should just rebase before hmmm

**Comment by igr** [comment]
@cirocosta that is ok, it will update the codebase.

**Comment by cirocosta** [comment]
👍

**Comment by cirocosta** [comment]
Hey @igorspasic , just updated master to follow the upstream, we had already removed the dependency we had on a cherry picked commit 👍

**Pull request merged**
