### PR TITLE
Rebase of upstream's master + rebase of 484 

### PR DESCRIPTION
**Pull request by cirocosta**

### CODE REVIEW

**Comment by cirocosta** [comment]
hmmm, maybe the best approach is just `push -f`ing. At least this highlights the amount of differences that went on (which could go unnoticed w/ a forced rebase)

**Comment by cirocosta** [comment]
@laissandrade  @igorspasic ok to rebase swarm with these changes? Maybe just rename to `launchpad` and keep going manually from there

**Comment by igr** [comment]
LGTM, and please rename as you said

**Comment by laissandrade** [comment]
Yes, looking good for me too.

**Comment by cirocosta** [comment]
nice, did it :)

**Pull request closed without merging**
